---
---
# Solved Lab | Connecting Python to SQL
---


## Solved Challenge

In this lab, the objective is to identify the customers who were active in both May and June, and how did their activity differ between months. To achieve this, follow these steps:

### 1. Establish a connection between Python and the Sakila database.

In [ ]:
# install sqlalchemy pymysql to connect to mysql database
!pip install sqlalchemy pymysql

In [ ]:
from sqlalchemy import create_engine
import pandas as pd

# Update with your credentials
user = "root"
password = "your_password"
host = "localhost"
port = 3306
database = "sakila"

# engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")
engine = create_engine("mysql+pymysql://root:ironhack13@localhost:3306/sakila")

In [12]:
import pandas as pd
pd.set_option('display.max_rows', None) # Show the full table in Jupyter

# ------------------------------------------------
# Test the connection by running a simple query
# ------------------------------------------------

# to fetch all rows of the customer table
print("Customer table:")
df_customer = pd.read_sql("SELECT * FROM `customer`;", engine) 
display(df_customer.head())
print(100*"-")

# to fetch all rows of the rental table
print("Rental table:")
df_rental = pd.read_sql("SELECT * FROM `rental`;", engine) 
display(df_rental.head())
print(100*"-")
# -----------------------------------------
# List all the tables in the database
# ------------------------------------------
print("All tables in the database:")
tables = pd.read_sql("SHOW TABLES;", engine)
display(tables)

# customer_id & rental_date columns are available in the same table `rental` 
# so we can fetch them together without needing to join with the `customer` table

# -----------------------------------------------------------------------------------
'''Fetch all tables and display the first 5 rows of each table
tables = tables.iloc[:, 0].tolist()  # Extract table names from the DataFrame
for table in tables:
    df = pd.read_sql(f"SELECT * FROM {table};", engine)
    display(df.head())'''
# -----------------------------------------------------------------------------------

Customer table:

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36,2006-02-15 04:57:20
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36,2006-02-15 04:57:20
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36,2006-02-15 04:57:20
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36,2006-02-15 04:57:20
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36,2006-02-15 04:57:20

----------------------------------------------------------------------------------------------------
Rental table:

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

----------------------------------------------------------------------------------------------------
All tables in the database:

              Tables_in_sakila
0                        actor
1                   actor_info
2                      address
3                     category
4                         city
5                      country
6                     customer
7                customer_list
8      customer_rental_summary
9                         film
10                  film_actor
11               film_category
12                   film_list
13                   film_text
14                   inventory
15                    language
16  nicer_but_slower_film_list
17                     payment
18                      rental
19      sales_by_film_category
20              sales_by_store
21                       staff
22                  staff_list
23                       store

'Fetch all tables and display the first 5 rows of each table\ntables = tables.iloc[:, 0].tolist()  # Extract table names from the DataFrame\nfor table in tables:\n    df = pd.read_sql(f"SELECT * FROM {table};", engine)\n    display(df.head())'

### 2. Write a Python function called `rentals_month`

This function retrieves rental data for a given month and year (passed as parameters) from the Sakila database as a Pandas DataFrame. The function should take in three parameters:
- `engine`: an object representing the database connection engine to be used to establish a connection to the Sakila database.
- `month`: an integer representing the month for which rental data is to be retrieved.
- `year`: an integer representing the year for which rental data is to be retrieved.

The function should execute a SQL query to retrieve the rental data for the specified month and year from the rental table in the Sakila database, and return it as a pandas DataFrame.

In [22]:
import pandas as pd

def rentals_month(month: int, year: int, engine) -> pd.DataFrame:
    """
    Retrieve rental data for a given month and year from the Sakila database.

    Parameters:
    - month: int, month number (1-12)
    - year: int, year (e.g., 2005)
    - engine: SQLAlchemy engine connected to the Sakila database
    
    Returns:
    - pandas DataFrame with columns:
        - customer_id
        - rental_date
        - ...
      containing only rentals from the specified month and year.
    """
    query = f"""
        SELECT *
        FROM rental
        WHERE MONTH(rental_date) = {month} AND YEAR(rental_date) = {year};
    """
    
    df_rentals = pd.read_sql(query, engine)
    
    if df_rentals.empty:
        print(f"No rentals found for {month:02d}/{year}")
    
    return df_rentals

# Example usage:
rentals_june_2005 = rentals_month(6, 2005, engine)
display(rentals_june_2005.head())
rentals_june_2005.info()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1158,2005-06-14 22:53:33,1632,416,2005-06-18 21:37:33,2,2006-02-15 21:30:53
1,1159,2005-06-14 22:55:13,4395,516,2005-06-17 02:11:13,1,2006-02-15 21:30:53
2,1160,2005-06-14 23:00:34,2795,239,2005-06-18 01:58:34,2,2006-02-15 21:30:53
3,1161,2005-06-14 23:07:08,1690,285,2005-06-21 17:12:08,1,2006-02-15 21:30:53
4,1162,2005-06-14 23:09:38,987,310,2005-06-23 22:00:38,1,2006-02-15 21:30:53

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2311 entries, 0 to 2310
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rental_id     2311 non-null   int64
 1   rental_date   2311 non-null   datetime64[ns]
 2   inventory_id  2311 non-null   int64
 3   customer_id   2311 non-null   int64
 4   return_date   2311 non-null   datetime64[ns]
 5   staff_id      2311 non-null   int64
 6   last_update   2311 non-null   datetime64[ns]
dtypes: datetime64[ns](3), int64(4)
memory usage: 126.5 KB

### 3. Develop a Python function called `rental_count_month` 

This function takes the DataFrame provided by `rentals_month` as input along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the selected month and year. 

The function should also include the month and year as parameters and use them to name the new column according to the month and year, for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".


*Hint: Consider making use of pandas [groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)*

In [28]:
import pandas as pd

# call function rentals_month
df= rentals_month(6, 2005, engine)

def rental_count_month(df, month, year):
    """
    Parameters:
    - df:  containing rental data table
    - month: int, month number (1-12)
    - year: int, year (e.g., 2005)
    
    Returns: 
    - new_df containing rentals number made by each `customer_id` during the selected month and year.
    """

    column_name = f"rentals_{month:02d}_{year}"
    
    df_count = (
        df.groupby("customer_id")
          .size()
          .reset_index(name=column_name)
    )
    
    return df_count

rental_count_month(df,5,2005)

     customer_id  rentals_05_2005
0              1                7
1              2                1
2              3                4
3              4                6
4              5                5
5              6                4
6              7                5
7              8                3
8              9                2
9             10                5
10            11                3
11            12                6
12            13                4
13            14                1
14            15                3
15            16                4
16            17                3
17            18                4
18            19                3
19            20                4
20            21                5
21            22                1
22            23                5
23            24                5
24            25                6
25            26                7
26            27                8
27            28                5
28            29                7
29            30                4
30            31               11
31            32                4
32            33                2
33            34                3
34            35                6
35            36                1
36            37                3
37            38                5
38            39                6
39            40                4
40            41                2
41            42                4
42            43                1
43            44                4
44            45                5
45            46                7
46            47                3
47            48                2
48            49                5
49            50                4
50            51                2
51            52                4
52            53                5
53            54                4
54            55                5
55            56                4
56            57                5
57            58                3
58            59                3
59            60                2
60            62                7
61            63                1
62            64                2
63            65                2
64            66                7
65            67                4
66            68                5
67            69                2
68            70                1
69            71                3
70            72                1
71            73                2
72            74                4
73            75                5
74            76                6
75            77                5
76            78                3
77            79                2
78            80                3
79            81                3
80            82                5
81            83                4
82            84                6
83            85                6
84            86                7
85            87                5
86            88                3
87            89                5
88            90                3
89            91                4
90            92                3
91            93                2
92            94                5
93            95                4
94            96                7
95            97                3
96            98                6
97            99                2
98           100                4
99           102                2
100          103                4
101          104                4
102          105                3
103          106                2
104          107                7
105          108                5
106          109                5
107          110                1
108          111                6
109          112                4
110          113                6
111          114                4
112          115                3
113          116                6
114          117                2
115          118                3
116          119                3
117          120                6
118          121                2
119          122                7
120          123                5
121          124                1
122          125                4
123          126                1
124          127                3
125          128                2
126          129                6
127          130                6
128          131                2
129          132                6
130          133                4
131          134                4
132          135                3
133          136                1
134          137                4
135          138                3
136          139                4
137          140                4
138          141                3
139          142                2
140          143                5
141          144                6
142          145                2
143          146                7
144          147                4
145          148                5
146          149                7
147          150                2
148          151                5
149          152                1
150          153                4
151          154                3
152          155                5
153          156                4
154          157                1
155          158                4
156          159                2
157          160                3
158          161                2
159          162                5
160          163                6
161          164                3
162          165                2
163          166                4
164          167                3
165          168                1
166          169                2
167          170                2
168          171                7
169          172                3
170          173                5
171          174                4
172          175                2
173          176                8
174          177                5
175          178                8
176          179                2
177          180                2
178          181                4
179          182                4
180          183                4
181          184                2
182          185                3
183          186                6
184          187                7
185          188                4
186          189                5
187          190                5
188          191                6
189          192                1
190          193                6
191          194                5
192          196                8
193          197                8
194          198                1
195          199                3
196          200                7
197          201                5
198          202                4
199          203                4
200          204                6
201          205                4
202          206                3
203          207                1
204          208                5
205          209                4
206          210                2
207          211                2
208          212                4
209          213                9
210          214                3
211          215                6
212          216                5
213          217                3
214          218                3
215          219                2
216          220                1
217          221                5
218          222                2
219          223                2
220          224                3
221          225                1
222          226                2
223          227                4
224          228                4
225          229                4
226          230                6
227          231                1
228          232                2
229          233                4
230          234                8
231          235                2
232          236                8
233          237                5
234          238                3
235          239                5
236          240                3
237          241                5
238          242                6
239          243                3
240          244                3
241          245                3
242          246                5
243          247                1
244          248                2
245          249                5
246          250                1
247          251                3
248          252                3
249          253                6
250          254                5
251          255                4
252          256                7
253          257                2
254          258                3
255          259                4
256          260                8
257          261                6
258          262                4
259          263                2
260          264                4
261          265                3
262          266                4
263          267                9
264          268                8
265          269                3
266          270                4
267          271                1
268          272                3
269          273                5
270          274                2
271          275                4
272          276                3
273          277                7
274          278                4
275          279                5
276          280                3
277          281                2
278          282                4
279          283                5
280          284                3
281          285                3
282          286                2
283          287                4
284          288                1
285          289                6
286          290                5
287          291                3
288          292                4
289          293                7
290          294                2
291          295                9
292          296                3
293          297                5
294          298                4
295          299                7
296          300                2
297          301                3
298          302                1
299          303                4
300          304                4
301          305                4
302          306                2
303          307                6
304          308                5
305          309                4
306          310                6
307          311                3
308          312                2
309          313                3
310          314                2
311          315                1
312          316                7
313          317                3
314          318                4
315          319                6
316          320                5
317          321                2
318          322                7
319          323                3
320          324                2
321          325                3
322          326                4
323          327                6
324          328                5
325          329                9
326          330                5
327          331                3
328          333                4
329          334                3
330          335                1
331          336                8
332          337                2
333          338                7
334          339                5
335          340                8
336          341                7
337          342                3
338          343                7
339          344                3
340          345                4
341          346                3
342          347                5
343          348                3
344          349                4
345          350                4
346          351                3
347          352                5
348          353                3
349          354                4
350          355                2
351          356                3
352          357                4
353          358                6
354          359                4
355          360                4
356          361                4
357          362                5
358          363                5
359          364                5
360          365                5
361          366                2
362          367                1
363          368                6
364          369                1
365          370                1
366          371                7
367          372                3
368          373                2
369          374                4
370          375                3
371          376                2
372          377                5
373          378                4
374          379                3
375          380                8
376          381                5
377          382                5
378          383                6
379          384                7
380          385                3
381          386                5
382          387                6
383          388                5
384          389                3
385          390                5
386          391                5
387          392                4
388          393                5
389          394                1
390          395                6
391          396                3
392          397                2
393          398                3
394          399                2
395          400                3
396          402                3
397          403                6
398          404                4
399          405                6
400          406                7
401          407                2
402          408                3
403          409                2
404          410                6
405          411                3
406          412                1
407          413                2
408          414                3
409          415                2
410          416                5
411          417                1
412          418                3
413          419                1
414          420                3
415          421                3
416          422                4
417          423                5
418          424                3
419          425                1
420          426                5
421          427                5
422          428                5
423          429                4
424          430                6
425          431                7
426          432                3
427          434                7
428          435                2
429          436                1
430          437                3
431          438                6
432          439                6
433          441                2
434          442                4
435          443                1
436          444                6
437          446                6
438          447                4
439          448                5
440          449                3
441          450                7
442          451                7
443          452                7
444          453                3
445          454               10
446          455                4
447          456                7
448          457                9
449          458                2
450          459                7
451          460                1
452          461                2
453          462                3
454          463                4
455          464                2
456          465                4
457          466                5
458          467                4
459          468                6
460          469                2
461          470                3
462          471                5
463          472                6
464          473                4
465          474                2
466          476                4
467          477                4
468          478                6
469          479                6
470          480                2
471          481                4
472          482                2
473          483                3
474          484                4
475          485                2
476          486                4
477          487                1
478          488                2
479          489                4
480          490                1
481          491                7
482          492                4
483          493                4
484          494                1
485          495                4
486          496                1
487          497                4
488          498                6
489          499                4
490          500                5
491          501                2
492          502                3
493          503                3
494          504                2
495          505                4
496          506                5
497          507                3
498          508                1
499          509                2
500          510                8
501          511                4
502          512                3
503          513                3
504          514                6
505          515                6
506          516                6
507          517                5
508          518                2
509          519                3
510          520                3
511          521                2
512          522                4
513          523                4
514          524                3
515          525                1
516          526                9
517          527                4
518          528                2
519          529                3
520          530                3
521          531                1
522          532                2
523          533                6
524          534                5
525          535                2
526          536                3
527          537                4
528          538                4
529          539                3
530          540                5
531          541                2
532          542                2
533          543                5
534          544                4
535          545                1
536          546                4
537          547                1
538          548                3
539          549                1
540          550                6
541          551                2
542          552                2
543          553                3
544          554                4
545          555                1
546          556                5
547          557                3
548          558                5
549          559                4
550          560                2
551          561                9
552          562                4
553          563                2
554          564                1
555          565                3
556          566                4
557          567                2
558          568                5
559          569                2
560          570                7
561          571                6
562          572                3
563          573                4
564          574                5
565          575                3
566          576                7
567          577                3
568          578                3
569          579                3
570          580                1
571          581                3
572          582                3
573          583                6
574          584                2
575          585                4
576          586                2
577          587                4
578          588                5
579          589                5
580          590                5
581          591                3
582          592                5
583          593                4
584          594                6
585          595                2
586          596                2

### 4. Create a Python function called `compare_rentals` 

This function takes two DataFrames as input containing the number of rentals made by each customer in different months and years. 

The function should return a combined DataFrame with a new 'difference' column, which is the difference between the number of rentals in the two months.

In [31]:
import pandas as pd

# customer 2 rental count in June 2005
df1 = rental_count_month(rentals_month(6, 2005, engine), 6, 2005)
# customer 2 rental count in April 2005
df2 = rental_count_month(rentals_month(5, 2005, engine), 5, 2005)

def compare_rentals(df1, df2):
    merged = pd.merge(df1, df2, on="customer_id", how="outer").fillna(0)
    
    # Identify rental columns
    col1 = df1.columns[1]
    col2 = df2.columns[1]
    
    merged["difference"] = merged[col2] - merged[col1]
    
    return merged


# Test the function 
# by comparing two dataframes containing rental counts 
# made by two different customers in different months and years
compare_rentals(df1, df2)

     customer_id  rentals_06_2005  rentals_05_2005  difference
0              1              7.0              2.0        -5.0
1              2              1.0              1.0         0.0
2              3              4.0              2.0        -2.0
3              4              6.0              0.0        -6.0
4              5              5.0              3.0        -2.0
5              6              4.0              3.0        -1.0
6              7              5.0              5.0         0.0
7              8              3.0              1.0        -2.0
8              9              2.0              3.0         1.0
9             10              5.0              1.0        -4.0
10            11              3.0              1.0        -2.0
11            12              6.0              2.0        -4.0
12            13              4.0              0.0        -4.0
13            14              1.0              5.0         4.0
14            15              3.0              0.0        -3.0
15            16              4.0              4.0         0.0
16            17              3.0              3.0         0.0
17            18              4.0              3.0        -1.0
18            19              3.0              6.0         3.0
19            20              4.0              3.0        -1.0
20            21              5.0              3.0        -2.0
21            22              1.0              3.0         2.0
22            23              5.0              3.0        -2.0
23            24              5.0              2.0        -3.0
24            25              6.0              2.0        -4.0
25            26              7.0              2.0        -5.0
26            27              8.0              1.0        -7.0
27            28              5.0              2.0        -3.0
28            29              7.0              1.0        -6.0
29            30              4.0              0.0        -4.0
30            31             11.0              0.0       -11.0
31            32              4.0              3.0        -1.0
32            33              2.0              1.0        -1.0
33            34              3.0              0.0        -3.0
34            35              6.0              2.0        -4.0
35            36              1.0              2.0         1.0
36            37              3.0              2.0        -1.0
37            38              5.0              0.0        -5.0
38            39              6.0              0.0        -6.0
39            40              4.0              1.0        -3.0
40            41              2.0              0.0        -2.0
41            42              4.0              1.0        -3.0
42            43              1.0              2.0         1.0
43            44              4.0              5.0         1.0
44            45              5.0              1.0        -4.0
45            46              7.0              3.0        -4.0
46            47              3.0              3.0         0.0
47            48              2.0              3.0         1.0
48            49              5.0              4.0        -1.0
49            50              4.0              5.0         1.0
50            51              2.0              3.0         1.0
51            52              4.0              1.0        -3.0
52            53              5.0              6.0         1.0
53            54              4.0              3.0        -1.0
54            55              5.0              3.0        -2.0
55            56              4.0              4.0         0.0
56            57              5.0              2.0        -3.0
57            58              3.0              3.0         0.0
58            59              3.0              3.0         0.0
59            60              2.0              3.0         1.0
60            61              0.0              1.0         1.0
61            62              7.0              2.0        -5.0
62            63              1.0              0.0        -1.0
63            64              2.0              3.0         1.0
64            65              2.0              2.0         0.0
65            66              7.0              1.0        -6.0
66            67              4.0              2.0        -2.0
67            68              5.0              0.0        -5.0
68            69              2.0              2.0         0.0
69            70              1.0              1.0         0.0
70            71              3.0              2.0        -1.0
71            72              1.0              3.0         2.0
72            73              2.0              2.0         0.0
73            74              4.0              1.0        -3.0
74            75              5.0              2.0        -3.0
75            76              6.0              2.0        -4.0
76            77              5.0              5.0         0.0
77            78              3.0              0.0        -3.0
78            79              2.0              3.0         1.0
79            80              3.0              0.0        -3.0
80            81              3.0              1.0        -2.0
81            82              5.0              2.0        -3.0
82            83              4.0              3.0        -1.0
83            84              6.0              3.0        -3.0
84            85              6.0              2.0        -4.0
85            86              7.0              1.0        -6.0
86            87              5.0              2.0        -3.0
87            88              3.0              1.0        -2.0
88            89              5.0              3.0        -2.0
89            90              3.0              0.0        -3.0
90            91              4.0              1.0        -3.0
91            92              3.0              2.0        -1.0
92            93              2.0              3.0         1.0
93            94              5.0              2.0        -3.0
94            95              4.0              1.0        -3.0
95            96              7.0              0.0        -7.0
96            97              3.0              0.0        -3.0
97            98              6.0              1.0        -5.0
98            99              2.0              1.0        -1.0
99           100              4.0              1.0        -3.0
100          101              0.0              1.0         1.0
101          102              2.0              3.0         1.0
102          103              4.0              2.0        -2.0
103          104              4.0              2.0        -2.0
104          105              3.0              4.0         1.0
105          106              2.0              2.0         0.0
106          107              7.0              2.0        -5.0
107          108              5.0              2.0        -3.0
108          109              5.0              7.0         2.0
109          110              1.0              2.0         1.0
110          111              6.0              1.0        -5.0
111          112              4.0              2.0        -2.0
112          113              6.0              2.0        -4.0
113          114              4.0              3.0        -1.0
114          115              3.0              3.0         0.0
115          116              6.0              1.0        -5.0
116          117              2.0              2.0         0.0
117          118              3.0              1.0        -2.0
118          119              3.0              3.0         0.0
119          120              6.0              2.0        -4.0
120          121              2.0              1.0        -1.0
121          122              7.0              2.0        -5.0
122          123              5.0              1.0        -4.0
123          124              1.0              4.0         3.0
124          125              4.0              1.0        -3.0
125          126              1.0              3.0         2.0
126          127              3.0              2.0        -1.0
127          128              2.0              2.0         0.0
128          129              6.0              0.0        -6.0
129          130              6.0              2.0        -4.0
130          131              2.0              3.0         1.0
131          132              6.0              0.0        -6.0
132          133              4.0              2.0        -2.0
133          134              4.0              4.0         0.0
134          135              3.0              2.0        -1.0
135          136              1.0              1.0         0.0
136          137              4.0              1.0        -3.0
137          138              3.0              2.0        -1.0
138          139              4.0              0.0        -4.0
139          140              4.0              0.0        -4.0
140          141              3.0              1.0        -2.0
141          142              2.0              3.0         1.0
142          143              5.0              2.0        -3.0
143          144              6.0              2.0        -4.0
144          145              2.0              1.0        -1.0
145          146              7.0              2.0        -5.0
146          147              4.0              2.0        -2.0
147          148              5.0              1.0        -4.0
148          149              7.0              1.0        -6.0
149          150              2.0              3.0         1.0
150          151              5.0              2.0        -3.0
151          152              1.0              2.0         1.0
152          153              4.0              0.0        -4.0
153          154              3.0              3.0         0.0
154          155              5.0              1.0        -4.0
155          156              4.0              2.0        -2.0
156          157              1.0              2.0         1.0
157          158              4.0              2.0        -2.0
158          159              2.0              4.0         2.0
159          160              3.0              0.0        -3.0
160          161              2.0              6.0         4.0
161          162              5.0              3.0        -2.0
162          163              6.0              0.0        -6.0
163          164              3.0              1.0        -2.0
164          165              2.0              1.0        -1.0
165          166              4.0              1.0        -3.0
166          167              3.0              3.0         0.0
167          168              1.0              2.0         1.0
168          169              2.0              2.0         0.0
169          170              2.0              3.0         1.0
170          171              7.0              1.0        -6.0
171          172              3.0              3.0         0.0
172          173              5.0              2.0        -3.0
173          174              4.0              2.0        -2.0
174          175              2.0              0.0        -2.0
175          176              8.0              5.0        -3.0
176          177              5.0              0.0        -5.0
177          178              8.0              0.0        -8.0
178          179              2.0              3.0         1.0
179          180              2.0              1.0        -1.0
180          181              4.0              1.0        -3.0
181          182              4.0              2.0        -2.0
182          183              4.0              1.0        -3.0
183          184              2.0              3.0         1.0
184          185              3.0              3.0         0.0
185          186              6.0              2.0        -4.0
186          187              7.0              1.0        -6.0
187          188              4.0              0.0        -4.0
188          189              5.0              1.0        -4.0
189          190              5.0              2.0        -3.0
190          191              6.0              2.0        -4.0
191          192              1.0              1.0         0.0
192          193              6.0              2.0        -4.0
193          194              5.0              2.0        -3.0
194          196              8.0              4.0        -4.0
195          197              8.0              8.0         0.0
196          198              1.0              5.0         4.0
197          199              3.0              1.0        -2.0
198          200              7.0              1.0        -6.0
199          201              5.0              3.0        -2.0
200          202              4.0              0.0        -4.0
201          203              4.0              1.0        -3.0
202          204              6.0              4.0        -2.0
203          205              4.0              0.0        -4.0
204          206              3.0              0.0        -3.0
205          207              1.0              6.0         5.0
206          208              5.0              1.0        -4.0
207          209              4.0              3.0        -1.0
208          210              2.0              1.0        -1.0
209          211              2.0              1.0        -1.0
210          212              4.0              0.0        -4.0
211          213              9.0              1.0        -8.0
212          214              3.0              5.0         2.0
213          215              6.0              2.0        -4.0
214          216              5.0              1.0        -4.0
215          217              3.0              2.0        -1.0
216          218              3.0              0.0        -3.0
217          219              2.0              1.0        -1.0
218          220              1.0              2.0         1.0
219          221              5.0              1.0        -4.0
220          222              2.0              5.0         3.0
221          223              2.0              1.0        -1.0
222          224              3.0              0.0        -3.0
223          225              1.0              2.0         1.0
224          226              2.0              0.0        -2.0
225          227              4.0              2.0        -2.0
226          228              4.0              2.0        -2.0
227          229              4.0              0.0        -4.0
228          230              6.0              2.0        -4.0
229          231              1.0              3.0         2.0
230          232              2.0              2.0         0.0
231          233              4.0              0.0        -4.0
232          234              8.0              1.0        -7.0
233          235              2.0              2.0         0.0
234          236              8.0              3.0        -5.0
235          237              5.0              2.0        -3.0
236          238              3.0              2.0        -1.0
237          239              5.0              6.0         1.0
238          240              3.0              3.0         0.0
239          241              5.0              2.0        -3.0
240          242              6.0              3.0        -3.0
241          243              3.0              1.0        -2.0
242          244              3.0              2.0        -1.0
243          245              3.0              6.0         3.0
244          246              5.0              5.0         0.0
245          247              1.0              3.0         2.0
246          248              2.0              2.0         0.0
247          249              5.0              4.0        -1.0
248          250              1.0              5.0         4.0
249          251              3.0              6.0         3.0
250          252              3.0              2.0        -1.0
251          253              6.0              3.0        -3.0
252          254              5.0              2.0        -3.0
253          255              4.0              0.0        -4.0
254          256              7.0              5.0        -2.0
255          257              2.0              3.0         1.0
256          258              3.0              0.0        -3.0
257          259              4.0              3.0        -1.0
258          260              8.0              1.0        -7.0
259          261              6.0              4.0        -2.0
260          262              4.0              1.0        -3.0
261          263              2.0              2.0         0.0
262          264              4.0              0.0        -4.0
263          265              3.0              1.0        -2.0
264          266              4.0              2.0        -2.0
265          267              9.0              3.0        -6.0
266          268              8.0              0.0        -8.0
267          269              3.0              6.0         3.0
268          270              4.0              2.0        -2.0
269          271              1.0              1.0         0.0
270          272              3.0              4.0         1.0
271          273              5.0              2.0        -3.0
272          274              2.0              6.0         4.0
273          275              4.0              1.0        -3.0
274          276              3.0              2.0        -1.0
275          277              7.0              1.0        -6.0
276          278              4.0              1.0        -3.0
277          279              5.0              2.0        -3.0
278          280              3.0              1.0        -2.0
279          281              2.0              2.0         0.0
280          282              4.0              3.0        -1.0
281          283              5.0              0.0        -5.0
282          284              3.0              3.0         0.0
283          285              3.0              0.0        -3.0
284          286              2.0              1.0        -1.0
285          287              4.0              3.0        -1.0
286          288              1.0              4.0         3.0
287          289              6.0              0.0        -6.0
288          290              5.0              1.0        -4.0
289          291              3.0              3.0         0.0
290          292              4.0              1.0        -3.0
291          293              7.0              3.0        -4.0
292          294              2.0              1.0        -1.0
293          295              9.0              1.0        -8.0
294          296              3.0              4.0         1.0
295          297              5.0              2.0        -3.0
296          298              4.0              1.0        -3.0
297          299              7.0              2.0        -5.0
298          300              2.0              3.0         1.0
299          301              3.0              3.0         0.0
300          302              1.0              2.0         1.0
301          303              4.0              3.0        -1.0
302          304              4.0              3.0        -1.0
303          305              4.0              1.0        -3.0
304          306              2.0              2.0         0.0
305          307              6.0              4.0        -2.0
306          308              5.0              1.0        -4.0
307          309              4.0              2.0        -2.0
308          310              6.0              1.0        -5.0
309          311              3.0              5.0         2.0
310          312              2.0              4.0         2.0
311          313              3.0              4.0         1.0
312          314              2.0              2.0         0.0
313          315              1.0              2.0         1.0
314          316              7.0              3.0        -4.0
315          317              3.0              1.0        -2.0